# Generated by Django 4.2.5 on 2024-07-26 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cArea_tematica', models.CharField(max_length=100, verbose_name='Área Temática')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad_Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cEntFinancia', models.CharField(max_length=100, unique=True, verbose_name='Entidad de Financiamiento')),
                ('lestado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion_Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cInstFinancia', models.CharField(max_length=100, unique=True, verbose_name='Institución de Financiamiento')),
                ('lestado', models.BooleanField(default=True, verbose_name='Estado')),
                ('entidad_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones', to='proyectos.entidad_financiamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpais', models.CharField(max_length=50, unique=True, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Apoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctipo_apoyo', models.CharField(max_length=50, verbose_name='Tipo de Apoyo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTipo_moneda', models.CharField(max_length=50, verbose_name='Tipo de Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTipoProyecto', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProyecto', models.CharField(max_length=20, verbose_name='Código de Proyecto')),
                ('nomProyecto', models.CharField(max_length=100, verbose_name='Nombre de Proyecto')),
                ('DescProyecto', models.CharField(max_length=300, verbose_name='Descripción de Proyecto')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Monto')),
                ('tipo_Cambio', models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Tipo de Cambio')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable IPEN')),
                ('responsableEnt', models.CharField(max_length=100, null=True, verbose_name='Responsable Entidad')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha Fin')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('cAreaTem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.area_tematica', verbose_name='Área Temática')),
                ('cEntFinan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.entidad_financiamiento', verbose_name='Entidad de Financiamiento')),
                ('cInstFinanc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.institucion_financiamiento', verbose_name='Institución de Financiamiento')),
                ('cTipoApoyo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.tipo_apoyo', verbose_name='Tipo de Apoyo')),
                ('cTipo_Moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.tipo_moneda', verbose_name='Tipo de Moneda')),
                ('cTipo_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.tipo_proyecto', verbose_name='Tipo de Proyecto')),
                ('cpais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.pais', verbose_name='País')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
        ),
    ]
