# Generated by Django 4.2.5 on 2024-08-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=100, verbose_name='nombre sede')),
                ('direccion_sede', models.CharField(max_length=200, verbose_name='direccion sede')),
                ('oficina_sede', models.CharField(max_length=200, verbose_name='oficina sede')),
                ('institucion_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sede', to='proyectos.institucion_financiamiento', verbose_name='institucion financiamiento')),
            ],
        ),
    ]
