# Generated by Django 4.2.5 on 2024-08-14 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='DescProyecto',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción de Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cEntFinan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.entidad_financiamiento', verbose_name='Entidad de Financiamiento'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cInstFinanc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.institucion_financiamiento', verbose_name='Institución de Financiamiento'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cTipoApoyo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.tipo_apoyo', verbose_name='Tipo de Apoyo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cTipo_Moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.tipo_moneda', verbose_name='Tipo de Moneda'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsableEnt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable Entidad'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_Cambio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tipo de Cambio'),
        ),
    ]
