# Generated by Django 4.2.5 on 2024-08-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_descproyecto_alter_proyecto_centfinan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='direccion_sede',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='direccion sede'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre_sede',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre sede'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='oficina_sede',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='oficina sede'),
        ),
    ]
