# Generated by Django 4.2.5 on 2024-07-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provincias', to='becarios.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=50, verbose_name='Distrito')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distritos', to='becarios.provincia')),
            ],
        ),
    ]
