# Generated by Django 4.2.5 on 2024-08-01 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_evento_responsableent'),
        ('proyectos', '0002_sede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('becarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Becas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_beca', models.CharField(max_length=100, verbose_name='nombre beca')),
                ('descripcion_beca', models.CharField(max_length=250, verbose_name='descripcion beca')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formacionacademica', models.CharField(max_length=100, verbose_name='formacion academica')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de documento')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_participante', models.CharField(choices=[('EXPERTO', 'EXPERTO'), ('PARTICIPANTE', 'PARTICIPANTE')], max_length=20, verbose_name='tipo participante')),
                ('procedencia', models.CharField(choices=[('EXTERNO', 'EXTERNO'), ('INTERNO', 'INTERNO')], max_length=20, verbose_name='tipo procedencia')),
                ('nom_participante', models.CharField(max_length=100, verbose_name='Nombre participante')),
                ('apellPate_participante', models.CharField(max_length=100, verbose_name='apellido paterno participante')),
                ('apellMate_participante', models.CharField(max_length=100, verbose_name='apellido materno participante')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Numero documento')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='telefono')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('cFormacion_academica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Participantes', to='becarios.formacionacademica', verbose_name='formacion academica')),
                ('cInstFinanc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Participantes', to='proyectos.institucion_financiamiento', verbose_name='Institución de Financiamiento')),
                ('cTipo_Documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Participantes', to='becarios.tipo_documento', verbose_name='Tipo de Documento')),
                ('cbeca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Participantes', to='becarios.becas', verbose_name='beca')),
                ('cdepartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Participantes', to='becarios.departamento', verbose_name='departamento')),
                ('cdistrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Participantes', to='becarios.distrito', verbose_name='distrito')),
                ('cpais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Participantes', to='proyectos.pais', verbose_name='País')),
                ('cprovincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Participantes', to='becarios.provincia', verbose_name='provincia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Participantes_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Participantes', to='eventos.evento', verbose_name='evento')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Participantes', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Participantes_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
    ]
