# Generated by Django 4.2.5 on 2024-08-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_sede'),
        ('becarios', '0002_becas_formacionacademica_tipo_documento_participante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becas',
            options={'verbose_name': 'Beca', 'verbose_name_plural': 'Becas'},
        ),
        migrations.AlterModelOptions(
            name='formacionacademica',
            options={'verbose_name': 'Formacion Academica', 'verbose_name_plural': 'Formaciones Academicas'},
        ),
        migrations.AlterModelOptions(
            name='tipo_documento',
            options={'verbose_name': 'Tipo Documento', 'verbose_name_plural': 'Tipos Documentos'},
        ),
        migrations.RemoveField(
            model_name='participante',
            name='cInstFinanc',
        ),
        migrations.AddField(
            model_name='participante',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Participantes', to='proyectos.sede', verbose_name='Sede'),
        ),
    ]
