# Generated by Django 4.2.5 on 2024-08-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_sede'),
        ('becarios', '0003_alter_becas_options_alter_formacionacademica_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='participante',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='participantes', to='proyectos.proyecto'),
        ),
    ]
