# Generated by Django 4.2.5 on 2024-08-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_evento_responsableent'),
        ('becarios', '0004_remove_participante_proyecto_participante_proyectos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='evento',
        ),
        migrations.AddField(
            model_name='participante',
            name='eventos',
            field=models.ManyToManyField(blank=True, related_name='participantes', to='eventos.evento'),
        ),
    ]
