# Generated by Django 4.2.5 on 2024-08-08 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_sede'),
        ('eventos', '0003_remove_evento_responsableent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('becarios', '0005_remove_participante_evento_participante_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='eventos',
            field=models.ManyToManyField(blank=True, related_name='Participantes', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='Participantes', to='proyectos.proyecto'),
        ),
        migrations.CreateModel(
            name='Det_EventoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_autorizacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='código autorización')),
                ('Cod_acta', models.CharField(blank=True, max_length=50, null=True, verbose_name='código acta')),
                ('Autorizacion', models.FileField(blank=True, null=True, upload_to='autorizaciones/', verbose_name='documento autorización')),
                ('acta', models.FileField(blank=True, null=True, upload_to='acta/', verbose_name='documento Acta')),
                ('Compromiso', models.CharField(blank=True, max_length=50, null=True, verbose_name='compromiso')),
                ('Objetivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='objetivo')),
                ('Informe', models.CharField(blank=True, max_length=50, null=True, verbose_name='informe')),
                ('Observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='observación')),
                ('actividad', models.CharField(blank=True, max_length=50, null=True, verbose_name='actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleEventoproyecto_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='det_eventoparticipante', to='eventos.evento', verbose_name='id evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='det_eventoparticipante', to='becarios.participante', verbose_name='id participante')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='det_eventoparticipante', to='proyectos.proyecto', verbose_name='id proyecto')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalleEventoproyecto_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'detalle evento y proyecto',
                'verbose_name_plural': 'detalles eventos y proyectos',
            },
        ),
    ]
