# Generated by Django 4.2.5 on 2024-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becarios', '0006_alter_participante_eventos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_eventoproyecto',
            name='Compromiso',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='compromiso'),
        ),
        migrations.AlterField(
            model_name='det_eventoproyecto',
            name='Objetivo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='objetivo'),
        ),
        migrations.AlterField(
            model_name='det_eventoproyecto',
            name='Observacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='observación'),
        ),
        migrations.AlterField(
            model_name='det_eventoproyecto',
            name='actividad',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='actividad'),
        ),
    ]
