# Generated by Django 4.2.5 on 2024-07-26 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTipoEvento', models.CharField(max_length=50, unique=True, verbose_name='Tipo_Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEvento', models.CharField(max_length=100, verbose_name='Codigo_Evento')),
                ('nomEvento', models.CharField(max_length=100, verbose_name='Nombre_Evento')),
                ('DescEvento', models.CharField(max_length=300, verbose_name='Descripción_Evento')),
                ('fechaInicio', models.DateField(verbose_name='Fecha_Inicio_Evento')),
                ('fechaFin', models.DateField(verbose_name='Fecha_Fin_Evento')),
                ('responsableEnt', models.CharField(max_length=100, null=True, verbose_name='Responsable_Entidad')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Monto')),
                ('tipo_Cambio', models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Tipo de Cambio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('cAreaTem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.area_tematica', verbose_name='Área_Temática')),
                ('cEntFinan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.entidad_financiamiento', verbose_name='Entidad_Financiamiento')),
                ('cInstFinanc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.institucion_financiamiento', verbose_name='Institución_Financiamiento')),
                ('cTipoApoyo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.tipo_apoyo', verbose_name='Tipo_Apoyo')),
                ('cTipoEvento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.tipo_evento', verbose_name='lTipo_Evento')),
                ('cTipo_Moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.tipo_moneda', verbose_name='Tipo_Moneda')),
                ('cpais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.pais', verbose_name='País_Eventos')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Evento_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Evento_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created'],
            },
        ),
    ]
