# Generated by Django 4.2.5 on 2024-07-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='cTipoEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.tipo_evento', verbose_name='Tipo_Evento'),
        ),
    ]
