# Generated by Django 4.2.5 on 2024-07-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_ctipoevento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='responsableEnt',
        ),
    ]
