# Generated by Django 4.2.5 on 2024-08-24 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_descproyecto_alter_proyecto_centfinan_and_more'),
        ('eventos', '0003_remove_evento_responsableent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='DescEvento',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción_Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cEntFinan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.entidad_financiamiento', verbose_name='Entidad_Financiamiento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cInstFinanc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.institucion_financiamiento', verbose_name='Institución_Financiamiento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cTipoApoyo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.tipo_apoyo', verbose_name='Tipo_Apoyo'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cTipo_Moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Eventos', to='proyectos.tipo_moneda', verbose_name='Tipo_Moneda'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha_Fin_Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_Cambio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tipo de Cambio'),
        ),
    ]
