# Generated by Django 4.2.5 on 2024-08-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_descevento_alter_evento_centfinan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable IPEN'),
        ),
        migrations.AddField(
            model_name='evento',
            name='responsableEnt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable Entidad'),
        ),
    ]
