# Generated by Django 4.2.5 on 2024-08-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_responsable_evento_responsableent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='responsable',
            field=models.CharField(max_length=100, verbose_name='Responsable IPEN'),
        ),
    ]
