# Generated by Django 4.2.5 on 2024-08-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Institucional'),
        ),
    ]
