# Generated by Django 4.2.5 on 2024-08-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_userprofile_correo_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='debe_cambiar_contraseña',
            field=models.BooleanField(default=True),
        ),
    ]
